routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('alumno', 'AlumnoController');
Route::resource('profesor', 'ProfesorController');
Route::resource('grado', 'GradosController');
Route::resource('grado_alumno', 'GradosAlumnosController');

app/GradoAlumno.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GradoAlumno extends Model
{
    protected $table = 'alumno_grado';

    protected $fillable = [
        'seccion','alumno_id','grado_id'
    ];

    public function relacion(){
        return $this->belongsToMany('App\GradoAlumno');
    }
    
    public function asociarAlumno(){
        
    }
    
}

resources/views/grado_alumno/create.blade.php
@extends('template.main')

@section('title','Asignacion de grado') 

@section('content')
    {!! Form::open(['route' => 'grado_alumno.store', 'method' => 'POST']) !!}
        
    <div class="form-group">
        {!! Form::label('seccion','Sección') !!}
        {!! Form::text('seccion',null ,[ 'class'=>'form-control', 'placeholder' => 'Sección', 'required' ]) !!}
    </div>

    <div class="form-group">
        {!! Form::label('alumno_id','Alumno') !!}
        {!! Form::select('alumno_id',$alumnos,null,['class'=>'form-control','placeholder'=>'Selecion un Alumno', 'required']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('grado_id','Grado') !!}
        {!! Form::select('grado_id',$grados,null,['class'=>'form-control','placeholder'=>'Selecion un Grado', 'required']) !!}
    </div>

    <div class="form-group">
        {!! Form::submit('Asignar Grado', [ 'class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}
@endsection

resources/views/grado_alumno/edit.blade.php
@extends('template.main')

@section('title','Asignacion de grado') 

@section('content')
    {!! Form::open(['route' => ['grado_alumno.update',$gradosAlumno->id], 'method' => 'PUT']) !!}
        
    <div class="form-group">
        {!! Form::label('seccion','Sección') !!}
        {!! Form::text('seccion',$gradosAlumno->seccion ,[ 'class'=>'form-control', 'placeholder' => 'Sección', 'required' ]) !!}
    </div>

    <div class="form-group">
        {!! Form::label('alumno_id','Alumno') !!}
        {!! Form::select('alumno_id',$alumnos,$gradosAlumno->alumno_id,['class'=>'form-control','placeholder'=>'Selecion un Alumno', 'required']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('grado_id','Grado') !!}
        {!! Form::select('grado_id',$grados,$gradosAlumno->grado_id,['class'=>'form-control','placeholder'=>'Selecion un Grado', 'required']) !!}
    </div>

    <div class="form-group">
        {!! Form::submit('Editar Asignación Grado', [ 'class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}
@endsection

resources/views/grado_alumno/index.blade.php
@extends('template.main')

@section('title','Grados y Alumnos') 

@section('content')
<br><a href="{{route('grado_alumno.create')}}" class="btn btn-success"> Asignar grado a Alumno</a><br><br>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Seccion</th>
                <th scope="col">Alumno</th>
                <th scope="col">Grado</th>
            </tr>
        </thead>
        <tbody>
        
                @foreach($gradosAlumno as $gradoAlumno)
                <tr>
                    <th scope="row">{{$gradoAlumno->id}}</th>
                    <td>{{$gradoAlumno->seccion}}</td>
                   
                    @foreach($alumnos as $alumno)
                        @if($alumno->id == $gradoAlumno->alumno_id )
                            <td>{{$alumno->nombre}}</td>
                        @endif
                    @endforeach


                    @foreach($grados as $grado)
                        @if($grado->id == $gradoAlumno->grado_id )
                            <td>{{$grado->nombre}}</td>
                        @endif
                    @endforeach

                    <td>
                        
                        {!! Form::open(['route' => ['grado_alumno.destroy',$gradoAlumno->id], 'method' => 'DELETE']) !!}
                            <a href="{{route('grado_alumno.edit',$gradoAlumno->id)}}" class="btn btn-danger"><i class="fas fa-pencil-alt"></i></a> 
                            <button type="submit" class="btn btn-warning" onclick="return confirm('Seguro que quieres elimanar {{$gradoAlumno->nombre}} ?')"><i class="fas fa-trash-alt"></i></button>
                        {!! Form::close() !!}
                        
                    </td>
                </tr>
                @endforeach
        </tbody>
    </table>
</div>
<div class="text-center">
    {!! $gradosAlumno->render() !!}
</div>

@endsection