routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('alumno', 'AlumnoController');
Route::resource('profesor', 'ProfesorController');
Route::resource('grado', 'GradosController');
Route::resource('grado_alumno', 'GradosAlumnosController');

resources/views/template/components/erros.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger alert-important" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach 
        </ul>
    </div>
@endif

resources/views/template/components/footer.blade.php
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <i class="fas fa-edit"></i>
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
        </div>
        <div class="col-6 col-md" style="text-align:right">
            <h3>Administracion del colegio</h3>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="text-muted p-2 text-dark" href="{{route('alumno.index')}}">Alumnos</a>
                <a class="text-muted p-2 text-dark" href="{{route('profesor.index')}}">Profesores</a>
                <a class="text-muted p-2 text-dark" href="{{route('grado.index')}}">Grados</a>
                <a class="text-muted p-2 text-dark" href="{{route('grado_alumno.index')}}">Grados y Alumnos</a>
            </nav>
        </div>
        
    </div>
</footer>

resources/views/template/components/nav.blade.php
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a style="text-decoration:none; color:black" href="/"><i class="fas fa-graduation-cap"></i> Colegio</h5></a>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="{{route('alumno.index')}}">Alumnos</a>
      <a class="p-2 text-dark" href="{{route('profesor.index')}}">Profesores</a>
      <a class="p-2 text-dark" href="{{route('grado.index')}}">Grados</a>
      <a class="p-2 text-dark" href="{{route('grado_alumno.index')}}">Grados y Alumnos</a>
    </nav>
  </div>